[package]
name = "cp_api"
version = "0.2.1"
authors = ["Russell Seifert <rseifert@checkpoint.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

description = "Check Point API library"
documentation = "https://docs.rs/cp_api"
repository = "https://github.com/seiruss/cp_api"
keywords = ["checkpoint", "api", "r80"]
readme = "README.md"

[dependencies]
reqwest = "0.9.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dev-dependencies]
rpassword = "2.1.0"
